services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: the-core-wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress-network.ini:/usr/local/etc/php/conf.d/wordpress-network.ini
    ports:
      - 8888:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1 
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_POST_REVISIONS', false);
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('WP_HTTP_BLOCK_EXTERNAL', false);
        define('WP_ACCESSIBLE_HOSTS', 'api.wordpress.org,*.wordpress.org');
        define('WP_AUTO_UPDATE_CORE', false);
        define('WPCF7_AUTOP', false);
        ini_set('openssl.cafile', '/etc/ssl/certs/ca-certificates.crt');
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
      UPLOAD_LIMIT: 3000000000
